# Generated by Django 4.1.7 on 2023-03-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_megano', '0013_alter_products_count_alter_products_href'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, unique=True, verbose_name='ID категории')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость единицы товара')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество товара')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка есть/нет')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_megano.products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
