# Generated by Django 4.1.7 on 2023-03-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0013_alter_products_count_alter_products_href'),
        ('app_cart', '0002_alter_cartitems_options_alter_cartitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_megano.products'),
        ),
    ]
