# Generated by Django 4.1.7 on 2023-03-04 14:55

import app_megano.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('href', models.URLField(unique=True, verbose_name='Ссылка')),
                ('image_src', models.ImageField(upload_to='images/category/src_<django.db.models.fields.AutoField>.jpg', verbose_name='Основное изображение')),
                ('image_alt', models.ImageField(upload_to='images/category/alt_<django.db.models.fields.AutoField>.jpg', verbose_name='Альтернативное изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость единицы товара')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество товара у продавца')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание товара')),
                ('fullDescription', models.TextField(blank=True, null=True, verbose_name='Полное описание товара')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка есть/нет')),
                ('href', models.URLField(unique=True, verbose_name='Ссылка на страницу товара')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления товара')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления товара')),
                ('category', models.ManyToManyField(related_name='products', to='app_megano.category')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Характеристика')),
                ('value', models.TextField(verbose_name='Значение характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название подкатегории')),
                ('href', models.URLField(unique=True, verbose_name='Ссылка')),
                ('image_src', models.ImageField(upload_to='images/category/src_sub_<django.db.models.fields.AutoField>.jpg', verbose_name='Основное изображение')),
                ('image_alt', models.ImageField(upload_to='images/category/alt_sub_<django.db.models.fields.AutoField>.jpg', verbose_name='Альтернативное изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rate', models.IntegerField(verbose_name='Рейтинг отзыва')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления отзыва')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_megano.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_megano.specifications', verbose_name='Особенности товара'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Название изображения')),
                ('imageURL', models.ImageField(upload_to='images/product/', verbose_name='Ссылка на изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_megano.products')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(related_name='category', to='app_megano.subcategories', verbose_name='Подкатегории'),
        ),
    ]
