# Generated by Django 4.1.7 on 2023-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0002_alter_category_options_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='category', to='app_megano.subcategories', verbose_name='Подкатегории'),
        ),
    ]
