# Generated by Django 4.1.7 on 2023-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0005_remove_category_subcategory_subcategories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='href',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='href',
        ),
        migrations.AlterField(
            model_name='category',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/alt_<django.db.models.fields.AutoField>.jpg', verbose_name='Альтернативное изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/src_<django.db.models.fields.AutoField>.jpg', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/alt_sub_<django.db.models.fields.AutoField>.jpg', verbose_name='Альтернативное изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/src_sub_<django.db.models.fields.AutoField>.jpg', verbose_name='Основное изображение'),
        ),
    ]
