# Generated by Django 4.1.7 on 2023-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0006_remove_category_href_remove_subcategories_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Альтернативное изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Альтернативное изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Основное изображение'),
        ),
    ]
