# Generated by Django 4.1.7 on 2023-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0007_alter_category_image_alt_alter_category_image_src_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='изображение'),
        ),
    ]
