# Generated by Django 4.1.7 on 2023-03-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0008_alter_category_options_alter_category_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='app_megano.category', verbose_name='Категория товара'),
        ),
    ]
