# Generated by Django 4.1.7 on 2023-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0010_alter_subcategories_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='index_sort',
            field=models.IntegerField(default=500, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='index_sort',
            field=models.IntegerField(default=500, verbose_name='Индекс сортировки'),
        ),
    ]
