# Generated by Django 4.1.7 on 2023-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0012_alter_category_options_alter_subcategories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='href',
            field=models.CharField(blank=True, max_length=650, null=True, unique=True, verbose_name='Ссылка на страницу товара'),
        ),
    ]
