# Generated by Django 4.1.7 on 2023-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0013_alter_products_count_alter_products_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='Отобразить на банере'),
        ),
        migrations.AddField(
            model_name='products',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Ограниченная серия'),
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=6, verbose_name='Рейтинг товара'),
            preserve_default=False,
        ),
    ]
