# Generated by Django 4.1.7 on 2023-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0014_products_banner_products_limited_products_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(verbose_name='Дата добавления отзыва'),
        ),
    ]
