# Generated by Django 4.1.7 on 2023-04-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_megano', '0015_alter_reviews_date'),
        ('app_users', '0002_alter_userprofile_phone'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.cities'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliveryType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app_orders.deliverytype'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_orders.paymenttype'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_orders.status'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app_orders.orders'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='app_megano.products'),
        ),
    ]
