# Generated by Django 4.1.7 on 2023-04-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_userprofile_phone'),
        ('app_orders', '0002_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app_users.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='app_users.cities'),
        ),
    ]
